# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "self-sensored-io"

[default.build.parameters]
beta_features = true
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = true
image_repositories = []
parameter_overrides = "TableName=\"self-sensored-io\""
region = "us-west-2"
resolve_s3 = true
s3_prefix = "self-sensored-io"
stack_name = "self-sensored-io"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
beta_features = true
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[personal.deploy.parameters]
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = true
image_repositories = []
parameter_overrides = "TableName=\"self-sensored-io\""
region = "us-west-2"
resolve_s3 = true
s3_prefix = "self-sensored-io"
stack_name = "self-sensored-io"
